<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Fitness Tracker Extreme</title>

    <!-- Bootstrap -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
   <link rel="stylesheet" type="text/css" href="style/stylesheet.css" />  
  </head>
  <body>
    <div class="container">
        <ul class="nav nav-tabs">
            <li role="presentation"><a href="index.php">Home</a></li>
            <li role="presentation"><a href="account.php">Account</a></li>
            <li role="presentation" class="active"><a href="exercise.php">Exercise</a></li>
            <li role="presentation"><a href="diet.php">Diet</a></li>
            <li role="presentation"><a href="stats.php">Stats</a></li>
            <li role="presentation"><a href="login.php">Login</a></li>
        </ul>
        
        <h1>What exercises have you done?</h1>
        
          <select class="select">
              <option value="211">Abdominal Crunches</option>
              <option value="212">Abdominal Leg Raise</option>
              <option value="213">Abdominal Twist, Seated, Machine</option>
              <option value="1">Aerobics, general</option>
              <option value="4">Aerobics, high impact</option>
              <option value="5">Aerobics, low impact</option>
              <option value="3">Aerobics, step, with 10-12 inch step</option>
              <option value="2">Aerobics, step, with 6-8 inch step</option>
              <option value="6">Archery (non-hunting)</option>
              <option value="7">Automobile repair</option>
              <option value="214">Back Butterfly</option>
              <option value="215">Back Extension</option>
              <option value="8">Backpacking, general</option>
              <option value="9">Badminton, competitive</option>
              <option value="10">Badminton, social, general</option>
              <option value="216">Bar Dip, Palms In, Neutral Grip</option>
              <option value="217">Barbell Military Press</option>
              <option value="218">Barbell Row, Bent-over</option>
              <option value="421033">Baseball</option>
              <option value="11">Basketball, game</option>
              <option value="12">Basketball, nongame, general</option>
              <option value="13">Basketball, officiating</option>
              <option value="14">Basketball, shooting baskets</option>
              <option value="15">Basketball, wheelchair</option>
              <option value="421380">Belly dancing</option>
              <option value="229">Bench (Chest) Press, Machine</option>
              <option value="219">Bench Press, Barbell</option>
              <option value="220">Bent Arm Barbell Pullover</option>
              <option value="221">Bent Arm Barbell Pullover and Press</option>
              <option value="222">Bent-Arm Lateral</option>
              <option value="223">Bent-Knee Sit-Up</option>
              <option value="224">Bent-Leg Kickbacks</option>
              <option value="225">Bent-Over Low-Pulley Side Lateral</option>
              <option value="226">Biceps Curl</option>
              <option value="18">Bicycling, 10-12 mph, light (cycling, biking, bike riding)</option>
              <option value="19">Bicycling, 12-14 mph, moderate (cycling, biking, bike riding)</option>
              <option value="20">Bicycling, 14-16 mph, vigorous (cycling, biking, bike riding)</option>
              <option value="21">Bicycling, 16-20 mph, very fast (cycling, biking, bike riding)</option>
              <option value="16">Bicycling, &lt;10 mph, leisure (cycling, biking, bike riding)</option>
              <option value="17">Bicycling, &gt;20 mph, racing (cycling, biking, bike riding)</option>
              <option value="22">Bicycling, BMX or mountain (cycling, biking, bike riding)</option>
              <option value="29">Billiards</option>
              <option value="30">Bowling</option>
              <option value="31">Boxing, in ring, general</option>
              <option value="32">Boxing, punching bag</option>
              <option value="33">Boxing, sparring</option>
              <option value="421078">Brazilian Jiu Jitsu</option>
              <option value="34">Broomball</option>
              <option value="227">Cable Crossover, High Pulley</option>
              <option value="228">Calf Raises, Single-Leg</option>
              <option value="35">Calisthenics (pushups, sit-ups), vigorous effort</option>
              <option value="36">Calisthenics, home, light/moderate effort</option>
              <option value="37">Canoeing, on camping trip</option>
              <option value="38">Canoeing, rowing, &gt;6 mph, vigorous effort</option>
              <option value="39">Canoeing, rowing, crewing, competition</option>
              <option value="40">Canoeing, rowing, light effort</option>
              <option value="41">Canoeing, rowing, moderate effort</option>
              <option value="42">Carpentry, general</option>
              <option value="230">Chin-Ups</option>
              <option value="421381">Chopping wood</option>
              <option value="43">Circuit training, general</option>
              <option value="44">Cleaning, heavy, vigorous effort</option>
              <option value="45">Cleaning, light, moderate effort</option>
              <option value="46">Coaching: football, soccer, basketball, etc.</option>
              <option value="47">Cooking or food preparation</option>
              <option value="421081">Crewing</option>
              <option value="48">Cricket (batting, bowling)</option>
              <option value="49">Croquet</option>
              <option value="50">Curling</option>
              <option value="421085">Curves Circuit Training</option>
              <option value="51">Dancing, aerobic, ballet or modern, twist</option>
              <option value="52">Dancing, ballroom, fast</option>
              <option value="53">Dancing, ballroom, slow</option>
              <option value="54">Dancing, general</option>
              <option value="55">Darts, wall or lawn</option>
              <option value="231">Deadlift, Straight Leg</option>
              <option value="232">Decline Bench Press</option>
              <option value="233">Decline Dumbbell Fly</option>
              <option value="234">Dips</option>
              <option value="56">Diving, springboard or platform</option>
              <option value="238">Dumbbell Press, One-Arm, Palm-In</option>
              <option value="235">Dumbbell Press, Seated, Palms-In</option>
              <option value="236">Dumbbell Row, One-Arm, Bent-Over</option>
              <option value="237">Dumbbell Row, Two-Arm, Bent-Over</option>
              <option value="330">Elliptical Trainer</option>
              <option value="57">Fencing</option>
              <option value="58">Fishing from boat, sitting</option>
              <option value="59">Fishing from river bank, standing</option>
              <option value="60">Fishing in stream, in waders</option>
              <option value="61">Fishing, general</option>
              <option value="62">Fishing, ice, sitting</option>
              <option value="239">Flat Dumbbell Fly</option>
              <option value="240">Flat Dumbbell Press</option>
              <option value="63">Football or baseball, playing catch</option>
              <option value="64">Football, competitive</option>
              <option value="65">Football, touch, flag, general</option>
              <option value="66">Frisbee playing, general</option>
              <option value="67">Frisbee, ultimate</option>
              <option value="241">Front Barbell Raise, Standing, Medium-Grip</option>
              <option value="242">Front Chin Up, Close-Grip, Palms Back</option>
              <option value="243">Front Chin Up, Reverse Close-Grip</option>
              <option value="244">Front Raises, Straight Arm</option>
              <option value="245">Front Squats, Barbell, Arms Crossed</option>
              <option value="68">Gardening, general</option>
              <option value="69">Golf, carrying clubs</option>
              <option value="70">Golf, miniature or driving range</option>
              <option value="71">Golf, pulling clubs</option>
              <option value="72">Golf, using power cart</option>
              <option value="73">Gymnastics, general</option>
              <option value="246">Hack Squat</option>
              <option value="74">Hacky sack</option>
              <option value="75">Handball, general</option>
              <option value="76">Handball, team</option>
              <option value="247">Heel Raise</option>
              <option value="421090">Hiking, climbing hills (carrying 10-20 lb load)</option>
              <option value="421093">Hiking, climbing hills (carrying &lt;10 lb load)</option>
              <option value="77">Hiking, cross country</option>
              <option value="248">Hip Abduction, Machine, Seated</option>
              <option value="249">Hip Flexor, Machine, Standing</option>
              <option value="78">Hockey, field</option>
              <option value="79">Hockey, ice</option>
              <option value="80">Horse grooming</option>
              <option value="81">Horseback riding, general</option>
              <option value="82">Horseback riding, trotting</option>
              <option value="83">Horseback riding, walking</option>
              <option value="84">Hunting, general</option>
              <option value="250">Hyperextensions</option>
              <option value="251">Incline Bench Press</option>
              <option value="252">Incline Dumbbell Curl</option>
              <option value="253">Incline Dumbbell Fly</option>
              <option value="254">Incline Lateral, Dumbbells</option>
              <option value="85">Jai alai</option>
              <option value="157">Jet skiing (riding jet ski, water ski-mobiling)</option>
              <option value="86">Judo, karate, kick boxing, tae kwan do</option>
              <option value="421094">Jumping jacks, vigorous</option>
              <option value="87">Kayaking</option>
              <option value="255">Kickbacks, Bent, 1-Arm, Dumbbell</option>
              <option value="256">Kickbacks, Bent, 2-Arm, Dumbbell</option>
              <option value="88">Kickball</option>
              <option value="421098">Kickboxing (including Turbo Jam)</option>
              <option value="23059332">LES MILLS GRIT™</option>
              <option value="89">Lacrosse</option>
              <option value="257">Lat Pulldown</option>
              <option value="258">Lateral Arm Raise, Machine</option>
              <option value="259">Lateral Raise, Dumbbell, Side</option>
              <option value="260">Leg Curls</option>
              <option value="261">Leg Extension</option>
              <option value="262">Leg Press</option>
              <option value="263">Leg Pull-In, Seated Flat Bench</option>
              <option value="264">Leg Raises, Hanging</option>
              <option value="23059330">Les Mills BODYATTACK™</option>
              <option value="23059334">Les Mills BODYBALANCE™/BODYFLOW®</option>
              <option value="23059331">Les Mills BODYCOMBAT™</option>
              <option value="23059328">Les Mills BODYPUMP™</option>
              <option value="23059329">Les Mills BODYSTEP™</option>
              <option value="23059333">Les Mills RPM™</option>
              <option value="421101">Line dancing</option>
              <option value="265">Lunge</option>
              <option value="266">Machine Fly</option>
              <option value="267">Machine Squat</option>
              <option value="90">Marching band, playing instrument(walking)</option>
              <option value="91">Marching, rapidly, military</option>
              <option value="421102">Martial arts</option>
              <option value="268">Mid Row, Chest Supported, Machine</option>
              <option value="92">Mild stretching</option>
              <option value="93">Motocross</option>
              <option value="94">Moving furniture, household</option>
              <option value="95">Moving household items, boxes, upstairs</option>
              <option value="96">Moving household items, carrying boxes</option>
              <option value="97">Mowing lawn, general</option>
              <option value="98">Mowing lawn, riding mower</option>
              <option value="99">Music playing, cello, flute, horn, woodwind</option>
              <option value="100">Music playing, drums</option>
              <option value="101">Music playing, guitar, classical, folk(sitting)</option>
              <option value="102">Music playing, guitar, rock/roll band(standing)</option>
              <option value="103">Music playing, piano, organ, violin, trumpet</option>
              <option value="269">Overhead Press, Barbell</option>
              <option value="270">Overhead Press, Machine, Seated</option>
              <option value="104">Paddleboat</option>
              <option value="271">Pec Dec Butterfly (Pectoral Fly)</option>
              <option value="272">Pelvic Lifts</option>
              <option value="421030">Pilates</option>
              <option value="105">Polo</option>
              <option value="273">Preacher Bench Medium-Grip Barbell Curl</option>
              <option value="275">Pull Ups (pull-ups)</option>
              <option value="421259">Pull-ups, vigorous</option>
              <option value="274">Pullover</option>
              <option value="421260">Punching bag</option>
              <option value="276">Push Ups (push-ups)</option>
              <option value="421267">Push-ups, vigorous</option>
              <option value="106">Pushing or pulling stroller with child</option>
              <option value="107">Race walking</option>
              <option value="108">Racquetball, casual, general</option>
              <option value="109">Racquetball, competitive</option>
              <option value="110">Raking lawn</option>
              <option value="421271">Rappelling</option>
              <option value="277">Rear Deltoid Raise</option>
              <option value="278">Reverse Sit-Up</option>
              <option value="279">Reverse Trunk Twist</option>
              <option value="111">Rock climbing, ascending rock</option>
              <option value="112">Rock climbing, rappelling</option>
              <option value="113">Roller blading (in-line skating)</option>
              <option value="114">Rope jumping, fast</option>
              <option value="115">Rope jumping, moderate, general</option>
              <option value="116">Rope jumping, slow</option>
              <option value="117">Rowing, stationary, light effort</option>
              <option value="118">Rowing, stationary, moderate effort</option>
              <option value="119">Rowing, stationary, very vigorous effort</option>
              <option value="120">Rowing, stationary, vigorous effort</option>
              <option value="121">Rugby</option>
              <option value="122">Running (jogging), 10 mph (6 min mile)</option>
              <option value="123">Running (jogging), 10.9 mph (5.5 min mile)</option>
              <option value="124">Running (jogging), 5 mph (12 min mile)</option>
              <option value="125">Running (jogging), 5.2 mph (11.5 min mile)</option>
              <option value="126">Running (jogging), 6 mph (10 min mile)</option>
              <option value="127">Running (jogging), 6.7 mph (9 min mile)</option>
              <option value="128">Running (jogging), 7 mph (8.5 min mile)</option>
              <option value="129">Running (jogging), 7.5 mph (8 min mile)</option>
              <option value="130">Running (jogging), 8 mph (7.5 min mile)</option>
              <option value="131">Running (jogging), 8.6 mph (7 min mile)</option>
              <option value="132">Running (jogging), 9 mph (6.5 min mile)</option>
              <option value="133">Running (jogging), in place</option>
              <option value="135">Running (jogging), training, pushing wheelchair</option>
              <option value="134">Running (jogging), up stairs</option>
              <option value="136">Sailing, boat/board, windsurfing, general</option>
              <option value="137">Sailing, in competition</option>
              <option value="280">Seated Biceps Curl</option>
              <option value="281">Seated Calf Raise</option>
              <option value="282">Seated Row, Floor, Machine</option>
              <option value="283">Seated, Low Lat Pull-In, Two-Arm</option>
              <option value="284">Shoulder Press</option>
              <option value="285">Shoulder Shrug</option>
              <option value="421296">Shoveling snow</option>
              <option value="138">Shuffleboard, lawn bowling</option>
              <option value="286">Side Bends, Barbell</option>
              <option value="287">Side Leg Raises</option>
              <option value="288">Sit-Ups</option>
              <option value="421298">Sit-ups, vigorous</option>
              <option value="139">Skateboarding</option>
              <option value="140">Skating, ice, 9 mph or less</option>
              <option value="141">Skating, ice, general</option>
              <option value="142">Skating, ice, rapidly, &gt; 9 mph</option>
              <option value="143">Skating, ice, speed, competitive</option>
              <option value="144">Skating, roller (rollerblading, roller blading)</option>
              <option value="145">Ski jumping (climb up carrying skis)</option>
              <option value="146">Ski machine, general</option>
              <option value="149">Skiing, cross-country, 2.5 mph, slow or light effort</option>
              <option value="148">Skiing, cross-country, 4-5 mph, moderate effort</option>
              <option value="151">Skiing, cross-country, 5-8 mph, vigorous effort</option>
              <option value="147">Skiing, cross-country, &gt;8.0 mph, racing</option>
              <option value="150">Skiing, cross-country, uphill, maximum effort</option>
              <option value="152">Skiing, downhill, light effort</option>
              <option value="153">Skiing, downhill, moderate effort</option>
              <option value="154">Skiing, downhill, vigorous effort, racing</option>
              <option value="155">Skiing, snow, general</option>
              <option value="156">Skiing, water</option>
              <option value="158">Skin diving, scuba diving, general</option>
              <option value="160">Sledding, tobogganing, bobsledding, luge</option>
              <option value="159">Slimnastics, jazzercise</option>
              <option value="161">Snorkeling</option>
              <option value="162">Snow shoeing</option>
              <option value="421301">Snowboarding</option>
              <option value="163">Snowmobiling</option>
              <option value="164">Soccer, casual, general</option>
              <option value="165">Soccer, competitive</option>
              <option value="166">Softball or baseball, fast or slow pitch</option>
              <option value="167">Softball, officiating</option>
              <option value="421303">Spinning®</option>
              <option value="168">Squash</option>
              <option value="289">Squat</option>
              <option value="169">Stair-treadmill ergometer, general</option>
              <option value="290">Standing Bar Curl, Machine</option>
              <option value="291">Standing Biceps Curl, Dumbell</option>
              <option value="292">Standing Calf Raises</option>
              <option value="293">Standing Medium-Grip Barbell Curl</option>
              <option value="294">Standing One-Arm Curl, Low Pulley</option>
              <option value="295">Standing One-Arm Dumbbell Curl</option>
              <option value="23">Stationary bike, general (bicycling, cycling, biking)</option>
              <option value="24">Stationary bike, light effort (bicycling, cycling, biking)</option>
              <option value="25">Stationary bike, moderate effort (bicycling, cycling, biking)</option>
              <option value="26">Stationary bike, very light effort (bicycling, cycling, biking)</option>
              <option value="27">Stationary bike, very vigorous effort (bicycling, cycling, biking)</option>
              <option value="28">Stationary bike, vigorous effort (bicycling, cycling, biking)</option>
              <option value="421304">Step-ups, vigorous</option>
              <option value="296">Straight Arm Dumbbell Pullover</option>
              <option value="209">Strength training (weight lifting, weight training)</option>
              <option value="170">Stretching, hatha yoga</option>
              <option value="171">Surfing, body or board</option>
              <option value="172">Swimming laps, freestyle, fast, vigorous effort</option>
              <option value="173">Swimming laps, freestyle, light/moderate effort</option>
              <option value="174">Swimming, backstroke, general</option>
              <option value="175">Swimming, breaststroke, general</option>
              <option value="176">Swimming, butterfly, general</option>
              <option value="177">Swimming, leisurely, general</option>
              <option value="178">Swimming, sidestroke, general</option>
              <option value="179">Swimming, synchronized</option>
              <option value="180">Swimming, treading water, fast/vigorous</option>
              <option value="181">Swimming, treading water, moderate effort</option>
              <option value="182">Table tennis, ping pong</option>
              <option value="421306">Tae Bo</option>
              <option value="421309">Tae Kwon Do</option>
              <option value="183">Tai chi</option>
              <option value="184">Teaching aerobics class</option>
              <option value="185">Tennis, doubles</option>
              <option value="186">Tennis, general</option>
              <option value="187">Tennis, singles</option>
              <option value="297">Toe Press</option>
              <option value="298">Triceps Extension</option>
              <option value="300">Triceps Pull-down</option>
              <option value="299">Triceps Push Down</option>
              <option value="188">Unicycling</option>
              <option value="301">Upright Row</option>
              <option value="302">V-Bar Chin Up, Neutral Grip, Palms In</option>
              <option value="303">Vertical Leg Lift, Knees Bent (Dip Bars)</option>
              <option value="304">Vertical Leg Lift, Knees Straight (Dip Bars)</option>
              <option value="189">Volleyball, beach</option>
              <option value="190">Volleyball, competitive, in gymnasium</option>
              <option value="191">Volleyball, noncompetitive; 6-9 member team</option>
              <option value="192">Walking, 2.0 mph, slow pace</option>
              <option value="194">Walking, 2.5 mph, downhill</option>
              <option value="193">Walking, 2.5 mph, leisurely pace</option>
              <option value="26688321">Walking, 3.0 mph, mod. pace</option>
              <option value="195">Walking, 3.0 mph, mod. pace, walking dog</option>
              <option value="196">Walking, 3.5 mph, brisk pace</option>
              <option value="197">Walking, 3.5 mph, uphill</option>
              <option value="198">Walking, 4.0 mph, very brisk pace</option>
              <option value="199">Walking, 4.5 mph, very, very brisk pace</option>
              <option value="200">Walking, 5.0 mph</option>
              <option value="201">Walking, carrying infant or 15-lb load</option>
              <option value="202">Walking, upstairs</option>
              <option value="203">Walking, using crutches</option>
              <option value="204">Wallyball, general</option>
              <option value="205">Water aerobics, water calisthenics</option>
              <option value="421311">Water jogging</option>
              <option value="206">Water polo</option>
              <option value="207">Water volleyball</option>
              <option value="210">Whitewater rafting, kayaking, or canoeing</option>
              <option value="421318">Wii Fit Advanced Step</option>
              <option value="421323">Wii Fit Free Run</option>
              <option value="421325">Wii Fit Free Step</option>
              <option value="421327">Wii Fit Island Run</option>
              <option value="421330">Wii Fit Rhythm Boxing</option>
              <option value="421331">Wii Fit Super Hula Hoop</option>
              <option value="421321">Wii Fit exercise (advanced or high intensity)</option>
              <option value="421322">Wii Fit exercise (beginner or low intensity)</option>
              <option value="421314">Wii baseball</option>
              <option value="421315">Wii bowling</option>
              <option value="421316">Wii boxing</option>
              <option value="421335">Wii golf</option>
              <option value="421334">Wii tennis</option>
              <option value="421336">Wrestling</option>
              <option value="305">Wrist Curl</option>
              <option value="306">Wrist Roller</option>
              <option value="421029">Yoga</option>
              <option value="20499218">Zumba® Fitness</option>
          </select>
        </p>
        
        <label>How Long:</label>
        <input autocomplete="off" class="text" id="minutes" name="minutes" size="4" type="text">
        <span>Minutes</span>
        <br >
        <button type="submit" class="btn btn-default">Submit</button>
        
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </body>
</html>